"""PostToolBatch post-edit checkpoint recall tests (issue #120, Workstream D).

Proves the Claude-only PostToolBatch lane end to end:
- the parser surface (extract_posttoolbatch_events /
  build_posttoolbatch_query / posttoolbatch_tool_summary) against the
  committed fixture: three ordered events, the singular compatibility
  shape, field filtering, 150/500 bounds, and the pinned `git-stash-pop`
  operation-token slug;
- the delivery contract: one bounded store decision per batch, the #117
  delivery-ledger suppression on a second identical batch, `moment=pretool`
  (never a posttoolbatch moment) in the decision log and the ledger, and
  raw payload strings never reaching the decision log;
- fail-open: malformed input and every store failure emit `{}` and exit 0;
- the registration contract: the exact Claude manifest block (no matcher,
  timeout 15), launcher routing (EVENT_MAP / TRANSLATED_HOOKS /
  NEEDS_NAMESPACE), and the deliberate Codex + ZCode absence.

The committed fixtures are generated by
`python tests/fixtures/posttoolbatch/generate.py` and their SHA-256
digests are pinned by test_fixture_digest.

Env isolation: ZMEM_STORE / ZMEM_DATA / ZMEM_MODELS_DIR /
ZMEM_MODEL_AUTODOWNLOAD are pinned to a scratch dir at MODULE level before
any module that could import storelib (the storelib STORE_PATH freeze
rule), and every store-touching subprocess gets a per-test clean env built
by _clean_env (the test_pretool_inject strip-list convention). Runs
standalone: python tests/test_posttoolbatch.py
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

# Store-isolation env MUST be pinned before any storelib import anywhere in
# this process (a test module importing storelib with ambient env freezes
# STORE_PATH to the operator's real store — the known co-run hazard). Hard
# assignment, NOT setdefault: an ambient ZMEM_STORE/ZMEM_DATA must never
# survive into this module's fixtures (PR #193 review CUBIC-2).
_MODULE_SCRATCH = tempfile.mkdtemp(prefix="zmem-postbatch-module-")
os.environ["ZMEM_STORE"] = os.path.join(_MODULE_SCRATCH, "store.sqlite")
os.environ["ZMEM_DATA"] = _MODULE_SCRATCH
os.environ["ZMEM_MODELS_DIR"] = os.path.join(_MODULE_SCRATCH, "missing-models")
os.environ["ZMEM_MODEL_AUTODOWNLOAD"] = "0"

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "skills" / "memory" / "scripts"
BODY = REPO_ROOT / "hooks" / "lib" / "zmem-recall-body.py"
LAUNCHER = REPO_ROOT / "hooks" / "zmem-launch.js"
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "posttoolbatch"

sys.path.insert(0, str(SCRIPTS))
sys.path.insert(0, str(SCRIPTS / "storelib"))

# Digests of the committed fixture bytes (regenerate with
# `python tests/fixtures/posttoolbatch/generate.py` and re-pin here if the
# fixture spec ever changes — the change must then be deliberate and
# reviewed, because #124 consumes expected.json by its exact path).
BATCH_SHA256 = "3f05b8771d06d98da35807cb4b8f65236d9b353b3cf86a4228f5aa8a7d69a84a"
EXPECTED_SHA256 = "0c8e28114844fe54d296f78b1334d88f4b5150a11fb6d116c9adc8c58b8d6d8e"

_BATCH_EVENTS = ["Edit src/a.py", "Write docs/guide.md", "Bash git stash pop"]

_STRIP_ENV = (
    "ZMEM_STORE", "ZMEM_DATA", "ZMEM_HOME", "ZMEM_NAMESPACE", "ZMEM_HOST",
    "ZMEM_QUERY_CONTEXT", "ZMEM_INJECT", "ZMEM_INJECT_TOKEN_BUDGET",
    "ZMEM_MODEL_AUTODOWNLOAD", "ZMEM_MODELS_DIR", "ZMEM_CONVENTION_INTERVAL",
    "ZMEM_SESSION", "CLAUDE_SESSION_ID", "ZCODE_SESSION_ID",
    "CLAUDE_PLUGIN_DATA", "ZCODE_PLUGIN_DATA",
    "ZMEM_EMBED_PROFILE", "ZMEM_TEST_NOW", "ZMEM_AUTO_REKEY",
    "ZMEM_PENDING_SIDECAR", "ZMEM_DELIVER_WINDOW_S", "ZMEM_LEDGER_CAP",
)


def _clean_env(tmp: str, **extra: str) -> dict:
    env = {k: v for k, v in os.environ.items() if k not in _STRIP_ENV}
    env.update({
        "ZMEM_STORE": os.path.join(tmp, "store.sqlite"),
        "ZMEM_DATA": tmp,
        "ZMEM_MODELS_DIR": os.path.join(tmp, "missing-models"),
        "ZMEM_MODEL_AUTODOWNLOAD": "0",
        "PYTHONUTF8": "1",
    })
    env.update(extra)
    return env


def _load_body():
    spec = importlib.util.spec_from_file_location(
        "zmem_recall_body_postbatch", BODY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _seed(env: dict, ns: str, content: str) -> None:
    r = subprocess.run(
        [sys.executable, str(SCRIPTS / "store.py"), "add",
         "--namespace", ns, "--type", "lesson", "--content", content,
         "--signal", "test", "--confidence", "0.9"],
        capture_output=True, text=True, env=env, timeout=120,
    )
    assert r.returncode == 0, f"seed failed: {r.stdout}\n{r.stderr}"


def _run_body(tmp: str, payload, ns: str = "user:global",
              store_path: str | None = None, **extra: str) -> tuple[str, int]:
    env = _clean_env(tmp, **extra)
    argv = [sys.executable, str(BODY),
            store_path or str(SCRIPTS / "store.py"), ns, "25000",
            "posttoolbatch"]
    r = subprocess.run(
        argv,
        input=payload if isinstance(payload, str) else json.dumps(payload),
        capture_output=True, text=True, env=env, timeout=120)
    return r.stdout, r.returncode


def _decision_lines(tmp: str) -> list[str]:
    log = Path(tmp) / "zmem-decisions.log"
    if not log.is_file():
        return []
    return [line for line in log.read_text(encoding="utf-8").splitlines()
            if "zmem-hook" in line]


class PostToolBatchTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.mkdtemp(prefix="zmem-postbatch-")
        self.addCleanup(shutil.rmtree, self._tmp, ignore_errors=True)

    # -- fixtures -----------------------------------------------------------

    def test_fixture_digest(self):
        # The committed fixture bytes are pinned so #124 can consume
        # expected.json by exact path and content. A spec change must
        # regenerate and re-pin deliberately.
        for name, want in (("batch.json", BATCH_SHA256),
                           ("expected.json", EXPECTED_SHA256)):
            data = (FIXTURES / name).read_bytes()
            self.assertEqual(
                hashlib.sha256(data).hexdigest(), want,
                f"{name} drifted; regenerate via "
                f"python tests/fixtures/posttoolbatch/generate.py and re-pin")
            self.assertTrue(data.endswith(b"\n"), f"{name} needs final LF")

    # -- parser surface (AC2) ------------------------------------------------

    def test_exact_batch_events(self):
        mod = _load_body()
        payload = json.loads((FIXTURES / "batch.json").read_text("utf-8"))
        self.assertEqual(mod.extract_posttoolbatch_events(payload),
                         _BATCH_EVENTS)
        # Singular compatibility shape yields exactly one event.
        singular = {"tool_name": "Edit", "tool_input": {"file_path": "src/a.py"}}
        self.assertEqual(mod.extract_posttoolbatch_events(singular),
                         ["Edit src/a.py"])
        # Field filtering: tool_response / result / unknown keys never pass.
        self.assertNotIn("IGNORED-RESPONSE",
                         json.dumps(mod.extract_posttoolbatch_events(payload)))
        self.assertNotIn("IGNORED-RESULT",
                         json.dumps(mod.extract_posttoolbatch_events(payload)))
        filtered = {"tool_uses": [
            {"name": "Bash", "input": {"command": "ls",
                                       "tool_response": "raw bytes",
                                       "cwd": "/x"}}]}
        self.assertEqual(mod.extract_posttoolbatch_events(filtered),
                         ["Bash ls"])
        # Missing list / non-object item / no retained field → no event.
        self.assertEqual(mod.extract_posttoolbatch_events(
            {"tool_uses": "nope"}), [])
        self.assertEqual(mod.extract_posttoolbatch_events(
            {"tool_uses": [42, {"name": "Bash"}]}), [])
        # Malformed payload carrying BOTH shapes parses once, never
        # duplicated (the singular form is a compatibility fallback).
        mixed = {"tool_uses": [{"name": "Edit",
                                "input": {"file_path": "a.py"}}],
                 "tool_name": "Edit", "tool_input": {"file_path": "b.py"}}
        self.assertEqual(mod.extract_posttoolbatch_events(mixed),
                         ["Edit a.py"])
        # 150-character field bound: a 200-char value is trimmed.
        long_val = "x" * 200
        trimmed = {"tool_uses": [{"name": "Edit",
                                  "input": {"file_path": long_val}}]}
        events = mod.extract_posttoolbatch_events(trimmed)
        self.assertEqual(len(events), 1)
        for part in events[0].split(" "):
            self.assertLessEqual(len(part), 150)
        self.assertEqual(events[0], "Edit " + "x" * 150)
        # Empty payload → no events.
        self.assertEqual(mod.extract_posttoolbatch_events({}), [])

    def test_query_and_tokens(self):
        mod = _load_body()
        payload = json.loads((FIXTURES / "batch.json").read_text("utf-8"))
        expected = json.loads(
            (FIXTURES / "expected.json").read_text("utf-8"))
        # Exact query bytes: events joined with one ASCII newline.
        self.assertEqual(mod.build_posttoolbatch_query(payload),
                         expected["query"])
        self.assertEqual(mod.build_posttoolbatch_query({}), "")
        # 500-character Unicode bound.
        big = {"tool_uses": [
            {"name": "Bash", "input": {"command": "é" * 400 + "y" * 400}}]}
        query = mod.build_posttoolbatch_query(big)
        self.assertLessEqual(len(query), 500)
        # Summary: tool_count, names, basenames only.
        summary = mod.posttoolbatch_tool_summary(payload)
        self.assertEqual(summary["tool_count"], 3)
        self.assertEqual(summary["names"], ["Edit", "Write", "Bash"])
        self.assertEqual(summary["basenames"], ["a.py", "guide.md"])
        self.assertEqual(
            set(summary), {"tool_count", "names", "basenames"})
        # Singular compatibility shape is reflected in the summary too
        # (PR #193 review CUBIC-3): a singular batch must not log empty
        # audit fields while its query still drives recall.
        singular_summary = mod.posttoolbatch_tool_summary(
            {"tool_name": "Edit", "tool_input": {"file_path": "src/a.py"}})
        self.assertEqual(singular_summary["tool_count"], 1)
        self.assertEqual(singular_summary["names"], ["Edit"])
        self.assertEqual(singular_summary["basenames"], ["a.py"])
        # Backslash paths normalize to the same basename on every host
        # (PR #193 review: os.path.basename is posix/no-op for "\\").
        win_summary = mod.posttoolbatch_tool_summary(
            {"tool_uses": [{"name": "Edit",
                            "input": {"file_path": "docs\\src\\a.py"}}]})
        self.assertEqual(win_summary["basenames"], ["a.py"])
        # Projection bound: element count is capped (PR #193 review
        # CUBIC-4) — 13 uses yield at most 12 names/basenames.
        many = mod.posttoolbatch_tool_summary(
            {"tool_uses": [{"name": f"T{i}",
                            "input": {"file_path": f"d{i}/f.py"}}
                           for i in range(13)]})
        self.assertEqual(many["tool_count"], 13)
        self.assertEqual(len(many["names"]), 12)
        self.assertEqual(len(many["basenames"]), 12)
        # Operation tokens. The batch token list is derive output over the
        # event strings; the pinned `git-stash-pop` slug is the Bash
        # command's own derivation (git ∈ _RUNNER_HEADS, pop ∈
        # _HAZARDOUS_SUBS), asserted through the REAL derive function.
        from ops_tokens import derive_ops_tokens
        self.assertEqual(derive_ops_tokens(*_BATCH_EVENTS),
                         ["guide.md", "a.py"])
        self.assertEqual("-".join(derive_ops_tokens("git stash pop")),
                         expected["ops_token"])
        self.assertEqual(expected["ops_token"], "git-stash-pop")
        # Empty batch: no events, empty query, empty summary.
        self.assertEqual(mod.posttoolbatch_tool_summary({}),
                         {"tool_count": 0, "names": [], "basenames": []})
        # Query cap is load-bearing: a multi-field payload whose raw event
        # text exceeds 500 chars must truncate to EXACTLY the cap (asserting
        # only "<= 500" would survive a deleted or inflated cap — PR #193
        # review T1). Internal whitespace runs normalize to single spaces.
        big = {"tool_uses": [
            {"name": "Bash", "input": {"command": "x" * 300 + "\t" + "y" * 300,
                                       "file_path": "p" * 300,
                                       "notebook_path": "q" * 300,
                                       "path": "r" * 300}},
            {"name": "Edit", "input": {"file_path": "s" * 300}},
        ]}
        big_query = mod.build_posttoolbatch_query(big)
        self.assertEqual(len(big_query), 500)
        self.assertNotIn("\t", big_query.split("\n")[0])
        self.assertEqual(
            mod.build_posttoolbatch_query(
                {"tool_uses": [{"name": "Bash",
                                "input": {"command": "a\tb\n  c"}}]}),
            "Bash a b c")
        # Decision-log projection: hostile names sanitize to structure-safe
        # tokens and the line stays ONE line (PR #193 review T7).
        mod._log_inject_decision(
            [], [], "silent", "empty-pool",
            session_id="s-sanitize", moment="pretool",
            batch=True,
            tool_names=["Ed it=x\ny"],
            path_basenames=["..\\..\\p q.py"])
        log_line = (Path(mod._data_dir()) / "zmem-decisions.log") \
            .read_text(encoding="utf-8").splitlines()[-1]
        self.assertIn("tools=Ed_it_x_y", log_line)
        self.assertIn("paths=.._.._p_q.py", log_line)

    # -- delivery + ledger (AC4) ----------------------------------------------

    def test_ledger_suppression(self):
        ns = "project:postbatch"
        lesson = ("postbatchcanary hazard: a later blind git stash pop can "
                  "apply a foreign pre-existing stash; verify git stash list "
                  "before any consuming command")
        _seed(_clean_env(self._tmp), ns, lesson)
        # A second lesson whose text contains the batch's derived tokens
        # (guide.md, a.py) whole AND enough query terms to clear the
        # lexical floor: the pretool strong-match carve-out must keep it
        # live across batches (re-delivered), while the non-matching
        # lesson stays suppressed (PR #193 review T4).
        carveout = ("edit write bash guide.md a.py postbatchcarveout: "
                    "after this git batch, update the guide and the "
                    "source file together")
        _seed(_clean_env(self._tmp), ns, carveout)
        payload = json.loads((FIXTURES / "batch.json").read_text("utf-8"))
        payload = dict(payload, session_id="s-postbatch-suppress")

        out, rc = _run_body(self._tmp, payload, ns=ns)
        self.assertEqual(rc, 0)
        ctx = json.loads(out.strip())["additionalContext"]
        self.assertIn("postbatchcanary", ctx)
        self.assertIn("postbatchcarveout", ctx)
        self.assertIn("<<<ZMEM_UNTRUSTED_FENCE>>>", ctx)
        lines = _decision_lines(self._tmp)
        self.assertEqual(len(lines), 1)
        self.assertIn("status=injected", lines[0])
        self.assertIn("moment=pretool", lines[0])
        self.assertIn("batch=1", lines[0])
        self.assertRegex(lines[0], r"ops=\d+")
        self.assertIn("tools=Edit,Write,Bash", lines[0])
        self.assertIn("paths=a.py,guide.md", lines[0])
        # Raw payloads never enter the decision log.
        log_text = "\n".join(lines)
        for raw in ("IGNORED-RESPONSE", "IGNORED-RESULT", "git stash pop"):
            self.assertNotIn(raw, log_text)
        # The ledger recorded the delivery under moment=pretool.
        ledger = _load_module(SCRIPTS / "storelib" / "delivery_ledger.py",
                              "delivery_ledger_postbatch")
        entries = ledger.delivered(str(self._tmp), "s-postbatch-suppress")
        self.assertEqual(len(entries), 2)
        for entry in entries:
            self.assertEqual(entry.get("moment"), "pretool")

        # Second identical batch: the non-matching lesson is excluded (the
        # ledger suppresses it) while the strong-matching carve-out lesson
        # is NOT excluded and re-delivers — both directions of the pretool
        # carve-out semantics in one run.
        out2, rc2 = _run_body(self._tmp, payload, ns=ns)
        self.assertEqual(rc2, 0)
        ctx2 = json.loads(out2.strip())["additionalContext"]
        self.assertIn("postbatchcarveout", ctx2)
        self.assertNotIn("postbatchcanary", ctx2)
        lines2 = _decision_lines(self._tmp)
        self.assertEqual(len(lines2), 2)
        self.assertIn("status=injected", lines2[1])
        self.assertIn("moment=pretool", lines2[1])
        self.assertIn("exc=1", lines2[1])

    # -- fail-open (AC5) -------------------------------------------------------

    def test_fail_open(self):
        payload = json.loads((FIXTURES / "batch.json").read_text("utf-8"))
        # (a) missing store file
        out, rc = _run_body(self._tmp, payload,
                            store_path=str(self._tmp) + "/absent/store.py")
        self.assertEqual(rc, 0)
        self.assertEqual(json.loads(out.strip() or '"-"'), {})
        # (b) store exits nonzero
        fake = Path(self._tmp) / "fail_store.py"
        fake.write_text("import sys\nsys.exit(3)\n", encoding="utf-8")
        out, rc = _run_body(self._tmp, payload, store_path=str(fake))
        self.assertEqual(rc, 0)
        self.assertEqual(json.loads(out.strip() or '"-"'), {})
        # (c) invalid JSON stdin → {} exit 0, with the empty-pool decision
        # line carrying the lane attribution but NO tools=/paths= segments
        # (empty lists render absent — PR #193 review T3).
        out, rc = _run_body(self._tmp, "{not json")
        self.assertEqual(rc, 0)
        self.assertEqual(json.loads(out.strip() or '"-"'), {})
        empty_lines = _decision_lines(self._tmp)
        self.assertTrue(empty_lines)
        self.assertIn("reason=empty-pool", empty_lines[-1])
        self.assertIn("moment=pretool", empty_lines[-1])
        self.assertIn("batch=1", empty_lines[-1])
        self.assertNotIn("tools=", empty_lines[-1])
        self.assertNotIn("paths=", empty_lines[-1])
        # (d) valid envelope with no rendered rows → {} exit 0. The fake
        # store also RECORDS its invocations, pinning the ONE-call-per-batch
        # selector contract inside the committed suite (PR #193 review T2 —
        # previously only the out-of-tree frozen check asserted this). The
        # query itself contains newlines, so args are newline-stripped when
        # recorded — one recorded line == one store invocation.
        empty = Path(self._tmp) / "empty_store.py"
        empty.write_text(
            "import json, sys\n"
            "open(sys.argv[0] + '.calls', 'a', encoding='utf-8').write("
            "' '.join(a.replace('\\n', ' ') for a in sys.argv[1:]) + '\\n')\n"
            "print(json.dumps({'results': [], 'omitted': 0, "
            "'reason': 'empty-pool', 'candidate_ids': []}))\n",
            encoding="utf-8")
        out, rc = _run_body(self._tmp, payload, store_path=str(empty))
        self.assertEqual(rc, 0)
        self.assertEqual(json.loads(out.strip() or '"-"'), {})
        calls = Path(str(empty) + ".calls").read_text(
            encoding="utf-8").splitlines()
        self.assertEqual(len(calls), 1)
        self.assertIn("recall", calls[0])
        self.assertIn("--for-injection", calls[0])
        self.assertIn("--no-bump", calls[0])
        self.assertIn("--json", calls[0])
        self.assertIn("--query", calls[0])
        self.assertIn("--namespace", calls[0])

    # -- registration (AC1) -----------------------------------------------------

    def test_claude_registration(self):
        cfg = json.loads(
            (REPO_ROOT / "hooks" / "hooks.claude.json").read_text("utf-8"))
        self.assertIn("PostToolBatch", cfg["hooks"])
        entries = cfg["hooks"]["PostToolBatch"]
        self.assertEqual(len(entries), 1)
        self.assertNotIn("matcher", entries[0])
        hook = entries[0]["hooks"][0]
        self.assertEqual(hook["type"], "command")
        self.assertEqual(
            hook["command"],
            'node "${CLAUDE_PLUGIN_ROOT}/hooks/zmem-launch.js" '
            'posttoolbatch-recall')
        self.assertEqual(hook["timeout"], 15)
        self.assertEqual(len(hook), 3)
        # Launcher routing: event map, translated set, namespace set.
        src = LAUNCHER.read_text(encoding="utf-8")
        self.assertIn('"posttoolbatch-recall": "PostToolBatch"', src)
        translated = src.split("const TRANSLATED_HOOKS")[1].split("]);")[0]
        self.assertIn('"posttoolbatch-recall"', translated)
        needs_ns = src.split("const NEEDS_NAMESPACE")[1].split("]);")[0]
        self.assertIn('"posttoolbatch-recall"', needs_ns)
        # Guardrail: the registered command's verb resolves to a real
        # wrapper (the lane-consistency check — a renamed route or wrapper
        # breaks this test, not the runtime).
        self.assertTrue((REPO_ROOT / "hooks"
                         / "zmem-posttoolbatch-recall.sh").is_file())
        # Wrapper wiring: mode string + sentinel + body invocation.
        wrapper = (REPO_ROOT / "hooks"
                   / "zmem-posttoolbatch-recall.sh").read_text("utf-8")
        self.assertIn('"posttoolbatch"', wrapper)
        self.assertIn("zmem-recall-body.py", wrapper)
        self.assertIn("<<<ZMEM_JSON>>>", wrapper)

    def test_codex_absence(self):
        for name in ("hooks.codex.json", "hooks.zcode.json"):
            cfg = json.loads(
                (REPO_ROOT / "hooks" / name).read_text("utf-8"))
            self.assertNotIn("PostToolBatch", cfg["hooks"], name)
            self.assertNotIn("posttoolbatch-recall",
                             json.dumps(cfg), name)


if __name__ == "__main__":
    unittest.main(verbosity=2)
