from __future__ import annotations

import argparse
import calendar
import contextlib
import hashlib
import json
import math
import os
import re
import shutil
import sqlite3
import struct
import subprocess
import sys
import time
import uuid
import glob
from datetime import datetime, timezone
from pathlib import Path

import embed_profiles as _profiles
from storelib.entity import link_memory_entities, relink_memory
from storelib.mine import _sanitize_error_text, _sanitize_pack_content
from storelib.schema import ALLOWED_SIGNALS, ALLOWED_TYPES, ALLOWED_TAINTS, GLOBAL_NAMESPACE, MAX_CONTENT_CHARS, SIGNAL_CONFIDENCE, STORE_PATH, _commit, _normalize_content, _parse_iso_to_epoch, now_iso
from storelib.write import CapturePolicyRefusal, _GLOBAL_NEAR_MISS_STEMS, _apply_capture_policy, _default_taint_for_signal, _detect_duplicate, _global_near_miss_key, _merge_on_dedup, _warn_degraded_embeddings_once, supersede_memory
from schema_meta import worse_taint  # noqa: F401

EXPORT_PACK_DEFAULT_PROJECT_LIMIT = 50

EXPORT_PACK_DEFAULT_GLOBAL_LIMIT = 15

EXPORT_PACK_DEFAULT_MIN_CONFIDENCE = 0.6

EXPORT_PACK_DEFAULT_MAX_BYTES = 32768



def _pack_query(conn: sqlite3.Connection, namespace: str, limit: int, min_confidence: float):
    """Live rows for one export-pack section, best candidates first."""
    return conn.execute(
        """SELECT type, signal, content FROM memory
           WHERE namespace=? AND superseded_at IS NULL AND confidence >= ?
           ORDER BY confidence DESC, (retrieval_count + surfaced_count) DESC,
                    ingestion_ts DESC
           LIMIT ?""",
        (namespace, min_confidence, limit),
    ).fetchall()

def _render_pack(namespace: str, store_path: str, project_rows, global_rows, max_bytes: int) -> str:
    """Render the Tier 1 markdown memory pack.

    Bullets are added greedily in document order (project section, then the
    global one). Each row is tested INDIVIDUALLY against the budget: if adding
    that bullet would push the UTF-8-encoded output past max_bytes it is
    skipped and counted toward the trailing omitted-count note, and the walk
    CONTINUES -- a later, smaller row still gets its bullet. (Skipping the
    rest of the pack after the first oversized row would let one long memory
    silently delete every other memory from the pack.) A bullet is only ever
    added whole, never truncated.

    Budget accounting: `max_bytes` is a budget over the WHOLE rendered pack
    measured as UTF-8 bytes -- structural framing included. Each candidate
    bullet is tested against the running `lines` (which already contains the
    header comment, title, and any section headings/"(none)" placeholders
    appended so far), so structural text DOES count toward the cap. The one
    exception is the trailing omitted-count footer (appended after the budget
    loop finishes), which is not budget-controlled -- it is a mandatory
    accounting note and must always render so an operator can see rows were
    dropped (#37 L1: earlier prose claimed structural text was "exempt from
    the cap", but the budget check sums all accumulated lines).

    Every rendered field goes through _sanitize_pack_content first: pack rows
    can be remote-authored (Tier 3 sync) and the pack is read as context by
    other agents, so no row may break out of its bullet.
    """
    today = time.strftime("%Y-%m-%d", time.gmtime())
    lines: list[str] = [
        f"<!-- Auto-generated by `zmem export-pack` from {store_path} on {today}. "
        "Do not hand-edit -- this file is overwritten by the next export-pack run. -->",
        f"# Memory pack: {namespace}",
        "",
    ]

    state = {"omitted": 0}

    def _emit_section(title: str, rows) -> None:
        lines.append(f"## {title}")
        if not rows:
            lines.append("(none)")
            lines.append("")
            return
        for row in rows:
            bullet = (
                f"- **[{_sanitize_pack_content(row['type'])}"
                f"/{_sanitize_pack_content(row['signal'])}]** "
                f"{_sanitize_pack_content(row['content'])}"
            )
            projected = len(("\n".join(lines + [bullet]) + "\n").encode("utf-8"))
            if projected > max_bytes:
                # Per-row skip, NOT a sticky stop: a single oversized memory
                # must not evict every smaller row behind it (including the
                # whole user:global section).
                state["omitted"] += 1
                continue
            lines.append(bullet)
        lines.append("")

    _emit_section("Project knowledge", project_rows)
    _emit_section(f"Cross-project lessons ({GLOBAL_NAMESPACE})", global_rows)

    if state["omitted"]:
        lines.append(
            f"*({state['omitted']} row(s) omitted to stay within --max-bytes={max_bytes})*"
        )

    return "\n".join(lines) + "\n"

def cmd_export_pack(
    conn: sqlite3.Connection,
    *,
    namespace: str,
    out: str | None = None,
    project_limit: int = EXPORT_PACK_DEFAULT_PROJECT_LIMIT,
    global_limit: int = EXPORT_PACK_DEFAULT_GLOBAL_LIMIT,
    min_confidence: float = EXPORT_PACK_DEFAULT_MIN_CONFIDENCE,
    max_bytes: int = EXPORT_PACK_DEFAULT_MAX_BYTES,
) -> int:
    """Write (or print) the Tier 1 markdown memory pack for `namespace`.
    Returns a process exit code."""
    project_rows = _pack_query(conn, namespace, project_limit, min_confidence)
    global_rows = _pack_query(conn, GLOBAL_NAMESPACE, global_limit, min_confidence)

    if not project_rows and not global_rows:
        print(
            f"[zmem] export-pack: no live memories at/above confidence "
            f"{min_confidence} in namespace={namespace} (or {GLOBAL_NAMESPACE}) "
            "-- an empty pack is almost certainly a wrong --namespace; refusing",
            file=sys.stderr,
        )
        return 2

    text = _render_pack(namespace, str(STORE_PATH), project_rows, global_rows, max_bytes)

    if out:
        out_path = Path(out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" disables Python's write-side newline translation so the
        # file keeps LF endings on Windows too (quiet diffs for a regenerated,
        # checked-in pack).
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"[zmem] export-pack: wrote {out_path} ({len(text.encode('utf-8'))} bytes)")
    else:
        sys.stdout.write(text)
    return 0

def cmd_export_jsonl(
    conn: sqlite3.Connection,
    *,
    out: str | None = None,
    namespace: str | None = None,
    include_superseded: bool = False,
) -> int:
    """Write one JSON object per line for LIVE rows (plus tombstoned rows too
    when include_superseded), sorted by ingestion_ts then id for deterministic
    diffs. No embedding fields -- bytes are not portable across machines;
    receivers rebuild via `reembed`."""
    clauses = []
    params: list = []
    if namespace:
        clauses.append("namespace=?")
        params.append(namespace)
    if not include_superseded:
        clauses.append("superseded_at IS NULL")
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    rows = conn.execute(
        f"""SELECT id, namespace, type, content, tags, source_ref, confidence, signal,
                   valid_from, valid_until, update_of, taint,
                   ingestion_ts, superseded_at, supersede_reason, merged_from,
                   trust_score
            FROM memory {where}
            ORDER BY ingestion_ts, id""",
        params,
    ).fetchall()

    # v11 (issue #61, 6.6/sync): outgoing link edges, grouped per src_id in one
    # pass. Links ARE carried in the JSONL (unlike entities, they are not
    # deterministically re-derivable per row — they depend on the neighbor set
    # at write time and on curated contradicts/supports). Only OUTGOING edges
    # are emitted: symmetric pairs are exported from BOTH endpoints' rows, so
    # a directed re-insert on ingest restores the table exactly. Extra keys
    # are backward-compatible: a pre-v11 validator reads fields via obj.get()
    # and never rejects unknown keys, so an older client can still ingest this
    # file (it just drops trust_score/links).
    link_map: dict = {}
    try:
        for e in conn.execute(
            "SELECT src_id, dst_id, relation, score, created_at FROM memory_link "
            "ORDER BY src_id, relation, dst_id"
        ).fetchall():
            link_map.setdefault(e["src_id"], []).append({
                "dst": e["dst_id"], "relation": e["relation"],
                "score": e["score"], "created_at": e["created_at"],
            })
    except sqlite3.OperationalError:
        pass  # memory_link absent (pre-v11 store never migrated) — export without links

    lines = []
    for r in rows:
        obj = {
            "id": r["id"],
            "namespace": r["namespace"],
            "type": r["type"],
            "content": r["content"],
            "tags": r["tags"],
            "source_ref": r["source_ref"],
            "confidence": r["confidence"],
            "signal": r["signal"],
            # v9 (issue #59, 4.6): the append-only lineage + provenance trust
            # columns round-trip with the row so a store rebuilt from its own
            # export preserves update history and taint exactly.
            "valid_from": r["valid_from"],
            "valid_until": r["valid_until"],
            "update_of": r["update_of"],
            "taint": r["taint"],
            "ingestion_ts": r["ingestion_ts"],
            "superseded_at": r["superseded_at"],
            "supersede_reason": r["supersede_reason"],
            "merged_from": r["merged_from"],
            # v11 (issue #61): the contradiction-ledger score round-trips
            # verbatim (it is event history, not derivable state), and so do
            # the row's outgoing link edges.
            "trust_score": r["trust_score"],
            "links": link_map.get(r["id"], []),
        }
        line = json.dumps(obj, ensure_ascii=False)
        # json.dumps already escapes every codepoint < 0x20 (\n, \r, and any
        # other ASCII control char), but U+2028/U+2029/U+0085 are line
        # terminators recognized by str.splitlines() (and some JS/JSONL
        # consumers) yet are NOT escaped by json.dumps since they are >=
        # 0x20. Left raw, one of these inside a content string would split
        # a single JSON object across multiple physical lines, shattering
        # the row for any reader that splits on line boundaries rather than
        # a bare "\n". Escape them explicitly so one JSON object == one line.
        line = (line.replace("\u2028", "\\u2028")
                    .replace("\u2029", "\\u2029")
                    .replace("\u0085", "\\u0085"))
        lines.append(line)
    text = "".join(line + "\n" for line in lines)

    if out:
        out_path = Path(out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"[zmem] export-jsonl: wrote {len(rows)} row(s) to {out_path}")
    else:
        sys.stdout.write(text)
    return 0

INGEST_MAX_CONTENT_CHARS = MAX_CONTENT_CHARS

# Shape guard for an incoming id: UUID-length hex-and-dashes. This is a
# charset/length guard, not a UUID parser -- the point is that an id from a
# remote file can never be an arbitrary string that some later consumer
# interpolates somewhere it shouldn't.

_INGEST_ID_RE = re.compile(r"^[0-9a-fA-F-]{36}$")

# Reject a forged-future ingestion_ts beyond this much clock skew. Recency is
# a ranking input (compute_score), so an unbounded future timestamp is a
# permanent top-of-recall boost for whoever wrote the sync file.

INGEST_MAX_FUTURE_SKEW_SECONDS = 86400

# Hard ceiling on one PHYSICAL line read from a JSONL sync file, in characters
# (str.readline()'s size argument counts characters in text mode, not bytes --
# this is not a byte cap). A hostile single-line file with no newlines at all
# would otherwise buffer the whole file into one Python string before
# _validate_sync_row ever runs, since the old `for line in f` iteration reads
# a full physical line regardless of its length. A legitimate row's content
# is already capped at INGEST_MAX_CONTENT_CHARS (65536) by validation, so 1
# MiB of physical line -- content plus JSON escaping plus every other field --
# is generous headroom for any real row and still bounds worst-case memory
# use per line.

MAX_LINE_CHARS = 1_048_576



def _validate_sync_row(obj: dict, lineno: int | None = None) -> dict:
    """Validate + normalize ONE remote-authored JSONL sync row.

    Returns a dict whose every field is already the right Python type for a
    direct bind into the memory table; raises ValueError (-> the caller counts
    the line malformed and continues) for anything that isn't recoverable.

    This exists because ingest-jsonl writes straight into the table, bypassing
    add_memory() and every guard argparse applies to a local `add`: without it
    a sync file can set any column to any JSON type. The concrete damage that
    motivated it: a STRING confidence is stored by SQLite as TEXT, and TEXT
    sorts above every numeric in SQLite's type ordering -- so it passes the
    `confidence >= ?` floor, hijacks export-pack's `ORDER BY confidence DESC`,
    and then crashes recall's compute_score with a ValueError on float().

    `lineno` is the 1-based physical line this row came from in the sync
    file, used ONLY to attribute the unknown-signal warning below to a line
    a human can go find; it is optional (None) for direct/programmatic
    callers that have no line to report.

    Recoverable (normalized, not rejected):
      - unknown/absent/non-str signal -> "none" (a stderr line is emitted
        whenever the key is present but unusable -- a made-up string, or a
        non-str value like a number; an absent/None signal is the normal,
        unremarkable case and stays silent)
      - non-numeric, non-finite, or out-of-range confidence -> the
        signal-derived default, clamped to [0.0, 1.0]
      - a far-future ingestion_ts -> clamped to now
      - absent/None optional string fields -> ""
    Rejected as malformed:
      - id absent or not UUID-shaped; namespace/content absent, non-str, or
        empty; type not in ALLOWED_TYPES; content over the size cap; any
        optional field present with a non-str, non-null type.
    """
    def _req_str(key: str) -> str:
        v = obj.get(key)
        if not isinstance(v, str):
            raise ValueError(f"field '{key}' must be a string, got {type(v).__name__}")
        if not v.strip():
            raise ValueError(f"field '{key}' is empty")
        return v

    def _opt_str(key: str) -> str:
        v = obj.get(key)
        if v is None:
            return ""
        if not isinstance(v, str):
            raise ValueError(f"field '{key}' must be a string or null, "
                             f"got {type(v).__name__}")
        return v

    mid = obj.get("id")
    if not isinstance(mid, str) or not _INGEST_ID_RE.match(mid):
        raise ValueError("field 'id' must be a 36-char UUID-shaped string")

    namespace = _req_str("namespace")
    # Apply the same global-near-miss rejection as add_memory() so a remote
    # peer (or a hand-authored sync file) cannot strand rows under `global` /
    # `userglobal` / etc. on this store — those rows would be unreachable from
    # every automatic hook (issue #18 "Related observation"). Reject as
    # malformed (caller counts the line and continues) rather than crashing;
    # canonicalize `user:global` to itself (no-op). (Final-critic F2.)
    ns_trimmed = namespace.strip()
    if ns_trimmed != GLOBAL_NAMESPACE:
        ns_key = _global_near_miss_key(ns_trimmed)
        if ns_key in _GLOBAL_NEAR_MISS_STEMS:
            raise ValueError(
                f"field 'namespace' value {ns_trimmed!r} looks like a "
                f"misspelling of the global namespace; use {GLOBAL_NAMESPACE!r}"
            )
    namespace = ns_trimmed
    content = _req_str("content")
    if len(content) > INGEST_MAX_CONTENT_CHARS:
        raise ValueError(f"field 'content' is {len(content)} chars, over the "
                         f"{INGEST_MAX_CONTENT_CHARS} limit")

    type_ = obj.get("type")
    if not isinstance(type_, str) or type_ not in ALLOWED_TYPES:
        raise ValueError(f"field 'type' must be one of {', '.join(ALLOWED_TYPES)}")

    # Signal is normalized, not rejected: an unknown signal costs the row its
    # confidence default, which is a fine outcome; losing the row is not. A
    # present-but-unrecognized value still gets a stderr line -- silent
    # coercion would otherwise hide a remote writer sending a signal this
    # version of zmem doesn't know about. Absent (None) signal is the normal,
    # unremarkable case and stays silent.
    raw_signal = obj.get("signal")
    if isinstance(raw_signal, str) and raw_signal in ALLOWED_SIGNALS:
        signal = raw_signal
    else:
        signal = "none"
        if raw_signal is not None:
            loc = f"line {lineno}: " if lineno is not None else ""
            print(f"[zmem] ingest-jsonl: {loc}unknown signal '{raw_signal}' "
                  f"treated as 'none'", file=sys.stderr)

    fallback_conf = SIGNAL_CONFIDENCE.get(signal, SIGNAL_CONFIDENCE["none"])
    raw_conf = obj.get("confidence")
    if raw_conf is None:
        confidence = fallback_conf
    else:
        try:
            confidence = float(raw_conf)
        except (TypeError, ValueError):
            confidence = fallback_conf
        # float() happily accepts "nan"/"inf": both would defeat the clamp
        # below (min/max propagate NaN) and poison the same ORDER BY.
        if not math.isfinite(confidence):
            confidence = fallback_conf
    confidence = max(0.0, min(1.0, confidence))

    tags = _opt_str("tags")
    source_ref = _opt_str("source_ref")
    supersede_reason = _opt_str("supersede_reason")
    valid_from = _opt_str("valid_from")
    valid_until = _opt_str("valid_until")
    update_of = _opt_str("update_of")
    ingestion_ts = _opt_str("ingestion_ts")
    superseded_at = _opt_str("superseded_at") or None
    merged_from = _opt_str("merged_from") or None

    # v9 (issue #59, 4.6): strict ISO-8601 UTC validation for the temporal
    # columns. Empty valid_until is legitimate ("never expires"); any
    # NON-EMPTY valid_from/valid_until must parse the store's exact writer
    # format (%Y-%m-%dT%H:%M:%SZ) or the row is counted malformed and NOT
    # stored ("Bad timestamp counted, not stored"). This closes the hole
    # where an unparsable timestamp was stored verbatim and silently defeated
    # the lexicographic as-of predicate.
    def _assert_valid_iso(value: str, field: str) -> None:
        # PR-review PRR-E (issue #59 review round): validate by PARSING, not by
        # comparing the epoch against 0 — _parse_iso_to_epoch returns 0.0 both
        # for unparsable input AND for a genuine 1970-01-01T00:00:00Z, so the
        # old epoch==0 sentinel wrongly refused the real epoch-zero timestamp.
        if value:
            try:
                time.strptime(value, "%Y-%m-%dT%H:%M:%SZ")
            except (ValueError, TypeError):
                raise ValueError(
                    f"field '{field}' is not a valid ISO-8601 UTC timestamp "
                    f"(expected YYYY-MM-DDTHH:MM:SSZ), got {value!r}"
                )

    _assert_valid_iso(valid_from, "valid_from")
    _assert_valid_iso(valid_until, "valid_until")

    # lineage invariant (issue #59, 4.4/4.6): valid_until is the exclusive end
    # of validity and is only EVER written at tombstone time, so a non-empty
    # valid_until implies a tombstone and vice versa. Enforce both directions
    # here so a remote file cannot resurrect a row or silently leave a
    # tombstone with an open-ended validity interval:
    #   - a TOMBSTONE (superseded_at set) with empty valid_until: inherit
    #     superseded_at (point-in-time as-of drops the superseded filter, so
    #     an empty valid_until would make the dead row valid at every T);
    #   - a LIVE row (no superseded_at) with non-empty valid_until: malformed
    #     (this writer only sets valid_until on tombstones; a live row carrying
    #     one is internally contradictory and would surface by default forever
    #     while being excluded at as-of=now).
    if superseded_at:
        if not valid_until:
            valid_until = superseded_at
        elif valid_until > superseded_at:
            # PR-review PRR-F (issue #59 review round): an authored
            # valid_until EARLIER than superseded_at is a legitimate,
            # preserved-as-authored interval ("factual validity ended before
            # the formal supersession" — pinned by
            # test_tombstone_authored_valid_until_is_preserved). But a
            # valid_until AFTER the death instant is incoherent with the
            # tombstone (this writer never produces it): refuse, store
            # nothing, count the row malformed.
            raise ValueError(
                f"tombstone coherence: 'valid_until' ({valid_until!r}) is "
                f"later than 'superseded_at' ({superseded_at!r}); a row "
                "cannot outlive its own tombstone (issue #59, 4.4)"
            )
    elif valid_until:
        raise ValueError(
            f"field 'valid_until' is set ({valid_until!r}) but the row is not "
            "superseded; this store only writes valid_until at tombstone time "
            "(issue #59, 4.4)"
        )

    # update_of references another row's id — enforce the same UUID-shape guard
    # as `id` so a remote file cannot plant an arbitrary string into the
    # append-only lineage chain (the comma-joined provenance columns already
    # rely on UUID-only ids — consolidate.py invariant).
    if update_of and not _INGEST_ID_RE.match(update_of):
        raise ValueError(
            f"field 'update_of' must be a 36-char UUID-shaped string, "
            f"got {update_of!r}"
        )

    # taint: absent (legacy v8 export) → the SAME signal-based derivation the
    # v8→v9 migration backfill applies (schema.py) and every write surface
    # shares (_default_taint_for_signal) — a grounded signal (test/compile/
    # lint/reviewer/user) defaults to trusted_internal, anything else to
    # untrusted_tool. PR-review PRR-G: the previous hardcoded
    # trusted_internal trust-escalated signal=none legacy rows relative to an
    # in-place migration and had no recompute path. Present with an unknown
    # value → malformed/refused ("Unknown taint value …", issue #59 4.7 —
    # there is deliberately no fourth rank to coerce to).
    raw_taint = obj.get("taint")
    if raw_taint is None:
        taint = _default_taint_for_signal(signal)
    elif not isinstance(raw_taint, str) or raw_taint not in ALLOWED_TAINTS:
        raise ValueError(
            f"field 'taint' must be one of {', '.join(ALLOWED_TAINTS)}, "
            f"got {raw_taint!r}"
        )
    else:
        taint = raw_taint

    # v11 (issue #61, sync): trust_score — optional float, clamped to
    # [0,1], absent/None defaults 1.0 (a pre-v11 export).
    # PRR-013 (swarm PR review): the previous silent 1.0 fallback let an
    # UNTRUSTED-taint row carrying garbage trust restore at FULL trust (the
    # max) — inconsistent with taint's strictness one screen up. Absent/None
    # still means 1.0 (a pre-v11 export — the normal legacy case); numeric
    # STRINGS coerce exactly like confidence's recoverable shape (the PR head
    # accepted "0.5" — no intra-PR regressions); any other non-numeric or
    # non-finite value makes the row malformed (fail-closed, counted, not
    # stored).
    raw_trust = obj.get("trust_score")
    if raw_trust is None:
        trust_score = 1.0
    else:
        if isinstance(raw_trust, bool) or not isinstance(
            raw_trust, (int, float, str)
        ):
            raise ValueError(
                f"field 'trust_score' must be a number, got "
                f"{type(raw_trust).__name__}"
            )
        try:
            trust_score = float(raw_trust)
        except ValueError:
            raise ValueError(
                f"field 'trust_score' must be a number, got {raw_trust!r}"
            )
        if not math.isfinite(trust_score):
            raise ValueError(
                f"field 'trust_score' must be finite, got {raw_trust!r}"
            )
    trust_score = max(0.0, min(1.0, trust_score))

    # v11 (issue #61, sync): outgoing link edges, optional list. Every entry
    # is validated fail-closed (a malformed EDGE makes the ROW malformed —
    # counted, not stored): dst must be UUID-shaped, relation must be a known
    # enum value, score finite in [0,1], created_at a string. The list rides
    # the validated dict under the reserved "_links" key (NOT a memory-table
    # column) and is consumed by cmd_ingest_jsonl's post-row pass.
    raw_links = obj.get("links")
    if raw_links is None:
        validated_links = []
    elif not isinstance(raw_links, list):
        raise ValueError(f"field 'links' must be a list or null, "
                         f"got {type(raw_links).__name__}")
    else:
        from storelib.links import LINK_RELATIONS
        validated_links = []
        for i, entry in enumerate(raw_links):
            if not isinstance(entry, dict):
                raise ValueError(f"field 'links[{i}]' must be an object, "
                                 f"got {type(entry).__name__}")
            dst = entry.get("dst")
            if not isinstance(dst, str) or not _INGEST_ID_RE.match(dst):
                raise ValueError(f"field 'links[{i}].dst' must be a 36-char "
                                 f"UUID-shaped string, got {dst!r}")
            relation = entry.get("relation")
            if not isinstance(relation, str) or relation not in LINK_RELATIONS:
                raise ValueError(
                    f"field 'links[{i}].relation' must be one of "
                    f"{', '.join(LINK_RELATIONS)}, got {relation!r}"
                )
            raw_score = entry.get("score", 0.0)
            try:
                score = float(raw_score)
            except (TypeError, ValueError):
                raise ValueError(f"field 'links[{i}].score' must be a number, "
                                 f"got {raw_score!r}")
            if not math.isfinite(score):
                raise ValueError(f"field 'links[{i}].score' must be finite, "
                                 f"got {raw_score!r}")
            created_at = entry.get("created_at", "")
            if not isinstance(created_at, str):
                raise ValueError(f"field 'links[{i}].created_at' must be a "
                                 f"string, got {created_at!r}")
            validated_links.append({
                "dst": dst, "relation": relation,
                "score": max(0.0, min(1.0, score)),
                "created_at": created_at,
            })

    if not ingestion_ts:
        ingestion_ts = now_iso()
    else:
        # A timestamp we cannot parse keeps today's graceful behavior (stored
        # verbatim; compute_score already treats an unparsable ingestion_ts as
        # unknown-age/neutral). Only a PARSED, implausibly-future one is
        # clamped -- that is the forgeable case.
        ts_epoch = _parse_iso_to_epoch(ingestion_ts)
        if ts_epoch > 0 and ts_epoch > time.time() + INGEST_MAX_FUTURE_SKEW_SECONDS:
            ingestion_ts = now_iso()

    return {
        "id": mid,
        "namespace": namespace,
        "type": type_,
        "content": content,
        "tags": tags,
        "source_ref": source_ref,
        "signal": signal,
        "confidence": confidence,
        "ingestion_ts": ingestion_ts,
        "valid_from": valid_from or ingestion_ts,
        "valid_until": valid_until,
        "update_of": update_of,
        "taint": taint,
        "superseded_at": superseded_at,
        "supersede_reason": supersede_reason,
        "merged_from": merged_from,
        # v11 (issue #61): carried through _ingest_row into the memory table;
        # "_links" is a reserved carriage key consumed by cmd_ingest_jsonl
        # (never a SQL column).
        "trust_score": trust_score,
        "_links": validated_links,
    }

def _ingest_row(conn: sqlite3.Connection, obj: dict, *, allow_tombstones: bool,
                capture_mode: str | None = None,
                dedup_cache: dict | None = None) -> str:
    """Apply one VALIDATED JSONL sync row (a _validate_sync_row result) to the
    local store.

    Returns 'added', 'tombstoned', 'tombstone_refused', 'deduped',
    'capture_refused', or 'skipped' -- the caller tallies these into the
    ingest-jsonl summary line. Malformed-row handling lives in the caller, so
    a bad row never reaches this function; the caller also catches anything
    raised here (a row that blows up must not abort the rest of the file).

    `allow_tombstones` gates the ONLY destructive thing an import can do to an
    existing local row (see cmd_ingest_jsonl's flag docs).

    `capture_mode` routes every INSERTED row through the same capture policy
    as ``add_memory`` (issue #35): prompt-injection-risk is tagged in ALL
    modes (a sync file is remote-authored data that can plant a poisoned
    memory surfacing verbatim into model context), and 'auto' mode
    additionally redacts secret-like content/tags and refuses rows whose
    source_ref looks like a secret. The existing-local-row path is NOT
    affected: local content is never overwritten by a sync import.
    """
    mid = obj["id"]
    namespace = obj["namespace"]
    type_ = obj["type"]
    content = obj["content"]
    tags = obj["tags"]
    source_ref = obj["source_ref"]
    signal = obj["signal"]
    confidence = obj["confidence"]
    ingestion_ts = obj["ingestion_ts"]
    valid_from = obj["valid_from"]
    valid_until = obj["valid_until"]
    update_of = obj["update_of"]
    taint = obj["taint"]
    superseded_at = obj["superseded_at"]
    supersede_reason = obj["supersede_reason"]
    merged_from = obj.get("merged_from")
    # v11 (issue #61): the row's authored trust_score (validated/clamped
    # upstream; 1.0 for a pre-v11 export). The "_links" carriage key is NOT
    # read here — cmd_ingest_jsonl applies links in a post-row pass so an
    # edge may reference an endpoint later in the file.
    trust_score = obj.get("trust_score", 1.0)

    # Existing-local-row short-circuit FIRST (issue #35 refinement): an id
    # already present locally is NEVER content-overwritten by a sync import --
    # the only thing it can receive is a tombstone. So resolve that path before
    # paying for capture policy (which only matters for rows we will actually
    # INSERT). This read-only SELECT runs under the writer lease held for the
    # whole ingest command, so there is no concurrent-writer race between this
    # probe and the BEGIN below. Capture policy thus applies ONLY to genuinely
    # new rows (live inserts + tombstoned-history inserts) -- exactly the rows
    # whose content/tags/source_ref will be written to disk.
    started_tx = False
    try:
        if not conn.in_transaction:
            conn.execute("BEGIN IMMEDIATE")
            started_tx = True

        local = conn.execute("SELECT superseded_at FROM memory WHERE id=?", (mid,)).fetchone()

        if local is not None:
            # id already known locally: local content is NEVER overwritten by a
            # sync import. The only mutation an existing row can receive here is
            # a tombstone, and only if the incoming row is superseded and the
            # local one is not already -- everything else is a no-op skip.
            if superseded_at and local["superseded_at"] is None:
                if not allow_tombstones:
                    if started_tx and conn.in_transaction:
                        conn.rollback()
                    return "tombstone_refused"
                ok = supersede_memory(conn, mid, supersede_reason, at=superseded_at)
                if started_tx and conn.in_transaction:
                    _commit(conn)
                return "tombstoned" if ok else "skipped"
            if started_tx and conn.in_transaction:
                conn.rollback()
            return "skipped"

        # The id is genuinely new -- capture policy now applies. _apply_capture_policy
        # is pure (no DB, no I/O -- see lines 893-929). It runs inside the open
        # transaction, so a CapturePolicyRefusal rolls it back before returning
        # (nothing was written yet: the only DB work so far is the read-only
        # existence SELECT above). This closes the prompt-injection-via-memory
        # vector on the sync write path: export-jsonl is the cross-store
        # propagation channel, so untrusted content -- even an already-superseded
        # history row -- is sanitized/tagged before it lands locally. Tagging is
        # mode-independent (prompt-injection-risk in ALL modes); secret
        # redaction/refusal only in 'auto'.
        #
        # NOTE on the dedup path below: capture policy is applied before
        # _detect_duplicate, so when this row dedups against a pre-existing local
        # row, _merge_on_dedup unions the (capture-policy-modified) tags into the
        # SURVIVING local row. That is intentional and symmetric with add_memory
        # (which applies capture policy before its own dedup-on-write merge): a
        # re-observation of risky content transfers its labels to the surviving
        # memory, and prompt-injection-risk is inert advisory metadata (fail-safe
        # direction). In auto mode, content redacted before dedup means a
        # secret-bearing near-duplicate will not match and is inserted as a
        # separate (redacted) row -- acceptable, since a redacted memory is by
        # definition a different memory.
        try:
            content, source_ref, tags, cap_warns = _apply_capture_policy(
                content=content,
                source_ref=source_ref,
                tags=tags,
                capture_mode=capture_mode,
            )
        except CapturePolicyRefusal as exc:
            if started_tx and conn.in_transaction:
                conn.rollback()
            print(f"[zmem] ingest-jsonl: refused row {mid}: {exc}", file=sys.stderr)
            return "capture_refused"
        for w in cap_warns:
            print(f"[zmem] ingest-jsonl: capture policy: {w}", file=sys.stderr)

        if superseded_at:
            # New locally, but already tombstoned upstream: insert as history so
            # future syncs stay consistent, without letting it participate in
            # dedup-on-write or recall -- it must not resurface, and it must not
            # silently absorb a live row into its (dead) dedup slot either.
            # Secret/injection handling is applied just above via
            # _apply_capture_policy (issue #35); no separate advisory scan here.
            shash = ""
            conn.execute(
                """INSERT INTO memory
                   (id, namespace, type, content, tags, source_ref, source_hash,
                    confidence, signal, valid_from, valid_until, update_of, taint,
                    superseded_at, supersede_reason,
                    ingestion_ts, retrieval_count, last_retrieved,
                    embedding, embedding_model, embedded_at, merged_from, content_norm,
                    trust_score)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,NULL,NULL,'',NULL,?,?,?)""",
                (mid, namespace, type_, content, tags, source_ref, shash,
                 confidence, signal, valid_from, valid_until, update_of, taint,
                 superseded_at, supersede_reason,
                 ingestion_ts, merged_from, _normalize_content(content),
                 trust_score),
            )
            # v10 (issue #60, sync decision): entities are NOT carried in the
            # JSONL (they are store-local derived data, like content_norm and
            # embeddings); ingest REBUILDS them by running the same
            # deterministic extractor as `add`. History rows link too —
            # --as-of recall reaches them via the entity lane.
            link_memory_entities(
                conn, mid, content=content, tags=tags, namespace=namespace,
            )
            if started_tx:
                _commit(conn)
            return "added"

        # Secret/injection handling is applied once above (for new rows) via
        # _apply_capture_policy (issue #35); no separate advisory scan here.
        existing, _sim, emb = _detect_duplicate(conn, content, namespace,
                                                 dedup_cache=dedup_cache)
        # v11 (issue #61, 6.2 — PR-review R1): the SAME write-time polarity
        # guard add_memory/update_memory apply. A remote row that contradicts
        # its dedup hit ("always X" vs "never X") must NOT be folded into the
        # keeper — the sync-restore contract restores ROWS, it does not get to
        # silently absorb a refutation into the row it refutes. Fall through
        # to the insert branch: the row lands as its own live row (still no
        # auto link generation / trust delta on ingest — deterministic
        # restore; a later `add`/`update`/`contradict` records the edge).
        if existing:
            from storelib.consolidate import dedup_polarity_conflict
            if dedup_polarity_conflict(conn, existing["id"], content):
                print(f"[zmem] ingest-jsonl: dedup skipped for row {mid}: "
                      f"polarity disagreement with {existing['id']}; stored "
                      "as its own row (contradictions never merge)",
                      file=sys.stderr)
                existing = None
        if existing:
            _merge_on_dedup(conn, existing["id"], confidence, signal, tags)
            # PR-review PRR-H (issue #59 review round): the surviving keeper
            # also absorbs the INCOMING row's taint — worst-of its own and the
            # synced row's — mirroring add_memory/update_memory. A remote
            # untrusted row folded into a local trusted keeper must upgrade
            # the keeper, not vanish.
            ex_row = conn.execute(
                "SELECT taint FROM memory WHERE id=?", (existing["id"],)
            ).fetchone()
            ex_base = (ex_row["taint"] if ex_row and ex_row["taint"]
                       else "trusted_internal")
            conn.execute(
                "UPDATE memory SET taint=? WHERE id=?",
                (worse_taint(ex_base, taint), existing["id"]),
            )
            # v10 (issue #60): dedup merge unioned tags onto the local keeper
            # — re-derive its entity links (same rule as add/update).
            relink_memory(conn, existing["id"])
            if started_tx:
                _commit(conn)
            return "deduped"

        shash = ""
        emb_model = (
            _profiles.embedding_model_name(_profiles.resolve_active_profile())
            if emb is not None
            else ""
        )
        embedded_at = now_iso() if emb is not None else None
        # Primary warning site for the ingest live-row insert (moved out of
        # _detect_duplicate so a no-op duplicate add cannot consume the one-time
        # flag). See _warn_degraded_embeddings_once.
        if emb is None:
            _warn_degraded_embeddings_once(content)
        conn.execute(
            """INSERT INTO memory
               (id, namespace, type, content, tags, source_ref, source_hash,
                confidence, signal, valid_from, valid_until, update_of, taint,
                superseded_at, ingestion_ts,
                retrieval_count, last_retrieved, embedding, embedding_model, embedded_at,
                merged_from, content_norm, trust_score)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NULL,?,0,NULL,?,?,?,?,?,?)""",
            (mid, namespace, type_, content, tags, source_ref, shash,
             confidence, signal, valid_from, valid_until, update_of, taint,
             ingestion_ts, emb, emb_model, embedded_at,
             merged_from, _normalize_content(content), trust_score),
        )
        if emb is not None:
            try:
                conn.execute(
                    "INSERT INTO memory_vec(embedding, memory_id) VALUES (?, ?)",
                    [emb, mid],
                )
            except sqlite3.OperationalError:
                pass  # vec0 table not available -- embedding stored in memory table only
        # v10 (issue #60, sync decision): rebuild entities on ingest by running
        # the SAME deterministic extractor as `add` (entities are derived
        # data; the JSONL carries none). Same transaction as the INSERT.
        link_memory_entities(
            conn, mid, content=content, tags=tags, namespace=namespace,
        )
        # Record this newly-inserted row in the per-ingest dedup cache so a
        # later row in the SAME batch with identical normalized content is
        # detected as a duplicate without a namespace rescan (#36 M9).
        if dedup_cache is not None:
            norm_new = _normalize_content(content)
            dedup_cache[(namespace, norm_new)] = mid
        if started_tx:
            _commit(conn)
        return "added"
    except Exception:
        if started_tx and conn.in_transaction:
            conn.rollback()
        raise

def cmd_ingest_jsonl(conn: sqlite3.Connection, *, in_path: str,
                     source_ref: str | None, allow_tombstones: bool = False,
                     capture_mode: str | None = None) -> int:
    """Import a JSONL sync file written by export-jsonl. Returns a process
    exit code: 2 if `in_path` cannot be read or contains no data lines at
    all, 0 otherwise (malformed/skipped/deduped rows do not fail the run --
    they are tallied and reported in the summary line).

    EVERY row is validated (_validate_sync_row) before it can touch the DB,
    and every row's application is individually guarded: one bad row is
    counted, reported with its line number, and the file keeps going. The
    summary line always prints, so "the run finished" and "every row landed"
    are never confused for each other.

    `allow_tombstones` controls whether an incoming row may kill a LIVE local
    row (see the --allow-tombstones flag help). Default off: a sync file is
    remote-authored data, and deleting local memory is the one irreversible
    thing it could ask for.

    Hostile input (nesting-bomb JSON, an oversized physical line, a bad
    encoding) is contained per-row/per-file: it never aborts the whole run,
    and the summary line is always printed regardless of how many rows were
    rejected. A row that raises mid-apply has any partial DB work rolled back
    via conn.rollback() before the file continues, so one row's failure
    between an INSERT and its own commit can never bleed into the next row's
    commit.
    """
    try:
        f = open(in_path, encoding="utf-8", newline="\n")
    except (OSError, UnicodeDecodeError) as e:
        print(f"[zmem] ingest-jsonl: cannot read {in_path}: {e}", file=sys.stderr)
        return 2

    added = tombstoned = tombstones_refused = deduped = skipped = malformed = 0
    capture_refused = 0
    links_added = links_skipped = 0
    first_refused_id = None
    saw_line = False
    decode_error = None
    # v11 (issue #61, sync): (src_id, validated_edges) per row carrying links.
    pending_links: list = []
    try:
        # Stream the file line by line instead of reading it whole into
        # memory first -- a giant hostile file would otherwise exhaust RAM
        # before a single row is even validated. newline="\n" makes readline()
        # split on a bare "\n" ONLY -- NOT the universal-newline default and
        # NOT str.splitlines(), either of which also breaks on U+2028/U+2029/
        # U+0085 (and other Unicode line separators). This file's own writer
        # (export_jsonl) escapes those three inside string values, but a
        # third-party JSONL writer might not; splitlines() would then shatter
        # one JSON object across several bogus "lines". Splitting on a bare
        # "\n" treats every embedded separator as ordinary string content
        # instead. rstrip("\r\n") tolerates CRLF-terminated files (each
        # returned line keeps its "\n", and a CRLF line keeps the "\r" too
        # since "\r" is not a split point). readline(MAX_LINE_CHARS) below
        # additionally bounds how much of ONE physical line is ever buffered.
        # Pre-build a per-ingest exact-match dedup cache (ONE namespace scan
        # total) so the per-row exact-match fallback is O(1) instead of
        # re-scanning the whole namespace per row (O(n²) — #36 M9). The cache
        # is updated in-memory as each row is inserted, so in-batch duplicates
        # are caught too. It lives in memory only; a rollback discards it with
        # the transaction (it never persists).
        dedup_cache: dict = {}
        try:
            for r in conn.execute(
                "SELECT id, content, namespace FROM memory WHERE superseded_at IS NULL"
            ).fetchall():
                norm = _normalize_content(r["content"])
                if norm:
                    dedup_cache[(r["namespace"], norm)] = r["id"]
        except Exception:
            # If the pre-scan fails (e.g. transient lock/IO error), pass None so
            # _detect_duplicate falls back to the original per-row namespace
            # scan. An EMPTY dict ({}) would be treated as AUTHORITATIVE ("no
            # duplicates exist") and silently disable exact-match dedup for the
            # whole ingest — None preserves correctness (#36 M9 final-critic).
            dedup_cache = None  # type: ignore[assignment]
        lineno = 0
        while True:
            # readline(MAX_LINE_CHARS) bounds how much of ONE physical line we
            # ever hold at once -- unlike `for line in f`, which buffers a
            # full physical line no matter how long it is. An empty return
            # here (as opposed to just "\n") means EOF.
            raw_line = f.readline(MAX_LINE_CHARS)
            if raw_line == "":
                break
            lineno += 1

            if len(raw_line) >= MAX_LINE_CHARS and not raw_line.endswith("\n"):
                # readline stopping at the cap without a trailing "\n" is
                # AMBIGUOUS: it could mean this physical line truly exceeds
                # MAX_LINE_CHARS (more of it still follows), or it could mean
                # the line is exactly MAX_LINE_CHARS chars and simply ends at
                # EOF with no trailing newline -- a perfectly valid final
                # line. One bounded lookahead read resolves it: "" means
                # nothing followed raw_line at all, so the line was complete
                # and just happened to land exactly on the cap -- fall
                # through and process it like any other line instead of
                # rejecting a well-formed final line as malformed.
                lookahead = f.readline(MAX_LINE_CHARS)
                if lookahead != "":
                    # There really is more of this physical line -- it is
                    # genuinely oversized. Reject it as malformed without
                    # ever accumulating it, then drain the rest (still
                    # bounded, chunk by chunk, starting from the lookahead
                    # chunk already read) so the NEXT read starts on the
                    # following line and lineno stays one-per-physical-line.
                    # Same as every other malformed line below: it had real
                    # content, so it counts toward "this file had data" even
                    # though the row itself is rejected -- a file consisting
                    # of nothing but one oversized line must not be reported
                    # as empty (exit 2) instead of malformed=1 (exit 0).
                    saw_line = True
                    print(f"[zmem] ingest-jsonl: malformed line {lineno}: line "
                          f"exceeds {MAX_LINE_CHARS} chars", file=sys.stderr)
                    malformed += 1
                    chunk = lookahead
                    while True:
                        # Stop draining once this physical line actually
                        # ends: either a newline was found, or we hit EOF (a
                        # short, non-full-cap chunk, possibly "", ends the
                        # line either way since no more cap-sized chunks can
                        # follow it).
                        if chunk.endswith("\n") or len(chunk) < MAX_LINE_CHARS:
                            break
                        chunk = f.readline(MAX_LINE_CHARS)
                    continue
                # else: lookahead == "" -- EOF right after raw_line, so the
                # line was complete at exactly MAX_LINE_CHARS chars. Fall
                # through to process raw_line normally below.

            line = raw_line.rstrip("\r\n").strip()
            if not line:
                continue
            saw_line = True
            try:
                obj = json.loads(line)
                if not isinstance(obj, dict):
                    raise ValueError("line is not a JSON object")
                obj = _validate_sync_row(obj, lineno)
            except Exception as e:
                # Broad on purpose: a per-line parse guard must never let hostile
                # input abort the whole file. A pathologically deeply nested JSON
                # value (a "nesting bomb") raises RecursionError from json.loads,
                # which is not a subclass of ValueError/JSONDecodeError and would
                # otherwise escape this guard, unwind past the per-row try/except
                # below, and kill the run mid-file with no summary line. Malformed
                # counting/reporting stays identical for every exception type.
                print(f"[zmem] ingest-jsonl: malformed line {lineno}: "
                      f"{_sanitize_error_text(str(e))}", file=sys.stderr)
                malformed += 1
                continue

            if source_ref:
                # --source-ref attributes this whole import batch to one place of
                # origin, overriding whatever source_ref the row carried in --
                # the original almost always points at a path that does not
                # exist on this machine.
                obj["source_ref"] = source_ref

            try:
                outcome = _ingest_row(conn, obj, allow_tombstones=allow_tombstones,
                                      capture_mode=capture_mode,
                                      dedup_cache=dedup_cache)
            except Exception as e:
                # A row that raises mid-apply must not abort the file and silently
                # drop every row after it. Roll back first: _ingest_row commits at
                # each of its return paths, so an exception between an INSERT and
                # its commit would otherwise leave a partial write open for the
                # NEXT row's commit to land.
                try:
                    conn.rollback()
                except Exception:
                    pass
                print(f"[zmem] ingest-jsonl: malformed line {lineno}: could not apply row: "
                      f"{type(e).__name__}: {_sanitize_error_text(str(e))}", file=sys.stderr)
                malformed += 1
                continue

            if outcome == "added":
                added += 1
            elif outcome == "tombstoned":
                tombstoned += 1
            elif outcome == "tombstone_refused":
                tombstones_refused += 1
                if first_refused_id is None:
                    first_refused_id = obj["id"]
            elif outcome == "capture_refused":
                capture_refused += 1
            elif outcome == "deduped":
                deduped += 1
            else:
                skipped += 1
            # v11 (issue #61, sync): collect the row's validated outgoing
            # edges for the post-row pass (an edge may reference an endpoint
            # later in the file, so links can never be applied per-row).
            # Collected on EVERY outcome — a deduped/skipped row's id never
            # lands locally, and the post-pass existence check skips its
            # edges (counted, reported) rather than failing the file.
            row_links = obj.get("_links")
            if row_links:
                pending_links.append((obj["id"], row_links))
    except (UnicodeDecodeError, OSError) as e:
        # Invalid UTF-8 can now surface mid-iteration (streaming, not a single
        # up-front read_text()) -- that's the UnicodeDecodeError case. OSError
        # covers a read failing mid-file for reasons that have nothing to do
        # with content: disk error, or the file getting truncated/replaced out
        # from under us while we're still reading it. Either way, record it
        # and fall through to the summary -- rows already applied before the
        # failure still count -- then exit 2, same as an unreadable file.
        decode_error = e
    finally:
        f.close()

    if decode_error is not None:
        print(f"[zmem] ingest-jsonl: cannot read {in_path}: {decode_error}", file=sys.stderr)
    elif not saw_line:
        print(f"[zmem] ingest-jsonl: {in_path} is empty -- nothing to ingest", file=sys.stderr)
        return 2

    if tombstones_refused:
        # ONE note, not one per row: a hostile or corrupt file could otherwise
        # bury every other warning under thousands of lines.
        print(f"[zmem] ingest-jsonl: refused {tombstones_refused} tombstone(s) against "
              f"LIVE local row(s) (first id: {first_refused_id}); those rows are "
              f"untouched. Re-run with --allow-tombstones ONLY if this file is your "
              f"own store's export, not a remote/cloud outbox.", file=sys.stderr)

    if capture_refused:
        # Rows refused by the capture policy (auto mode: source_ref looked like a
        # secret). NOT written. One summary note, not per-row, for the same
        # noise-suppression reason as tombstones_refused.
        print(f"[zmem] ingest-jsonl: refused {capture_refused} row(s) under the "
              f"capture policy (secret-like source_ref in 'auto' mode); those rows are "
              f"NOT stored. Re-ingest with --capture-mode reviewed/manual only "
              f"if you have verified the source_ref is safe.", file=sys.stderr)

    # v11 (issue #61, sync): apply collected link edges AFTER every row has
    # landed (endpoints may appear anywhere in the file). Each edge is
    # re-inserted as the SINGLE directed row it was exported as — symmetric
    # pairs arrive as two rows (one per endpoint), so the table restores
    # exactly, and created_at is preserved for byte-identical re-export. No
    # trust deltas here, ever: the exported trust_score was restored verbatim
    # with its row, and re-applying event history would double-count it
    # (also what keeps re-ingest of the same file an exact no-op).
    if pending_links:
        from storelib.links import add_link
        known = {r[0] for r in conn.execute("SELECT id FROM memory").fetchall()}
        for src, entries in pending_links:
            if src not in known:
                links_skipped += len(entries)
                continue
            for e in entries:
                if e["dst"] not in known:
                    links_skipped += 1
                    continue
                try:
                    if add_link(
                        conn, src, e["dst"], e["relation"], e["score"],
                        created_at=e["created_at"] or None,
                    ):
                        links_added += 1
                except ValueError:
                    links_skipped += 1
        # PRR-005 (swarm PR review): every other commit site in this file
        # goes through _commit's busy_retry — a raw conn.commit() here let a
        # transient SQLITE_BUSY raise past the summary line and drop the
        # run's collected links.
        _commit(conn)

    print(f"[zmem] ingest-jsonl: added={added} tombstoned={tombstoned} "
          f"tombstones_refused={tombstones_refused} capture_refused={capture_refused} "
          f"deduped={deduped} skipped={skipped} malformed={malformed} "
          f"links_added={links_added} links_skipped={links_skipped}")
    return 2 if decode_error is not None else 0
